project_name: proji

before:
    hooks:
        - go mod download

builds:
    -
        main: ./cmd/proji/main.go
        goos:
            - linux
            - darwin
            - windows
        goarch:
            - amd64
            - arm64
        targets:
            - linux_amd64
            - linux_arm64
            - darwin_amd64
            - darwin_arm64
            - windows_amd64
        env:
            - CGO_ENABLED=0
        ldflags:
            - -s -w -X github.com/nikoksr/proji/internal/buildinfo.AppVersion={{.Version}}

archives:
    -   replacements:
            darwin: macOS
            linux: Linux
            windows: Windows
            amd64: x86_64

        format_overrides:
            -   goos: windows
                format: zip

        name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

        files:
            - LICENSE
            - README.md

checksum:
    name_template: "checksums.txt"

snapshot:
    name_template: "{{ .Tag }}"

changelog:
    skip: false
    use: github-native
